### ISSUE TITLE
好像失效了

### ISSUE THREAD

**Issue by Sherry720** [ronething/ZhiHuCollectionToPDF#1]

**Comment by ronething** [comment]
试了一下好像有些 title 取不到。

https://github.com/ronething/ZhiHuCollectionToPDF/blob/54982f363a55dbb193bdf9ee2533e4b86ead49a6/zhihucollection_pool.py#L49

```python
title = i.h2.a.get_text()
            try:
                topicUrl = i.find("a", {"class": "toggle-expand"}).get('href')
```

将 `title = i.h2.a.get_text()` 放进 try 里面就可以了。
